import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "IPv4Premium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script
          id="strip-extension-attrs"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html:
              "(function(){var A=['cz-shortcut-listen','bis_register','bis_skin_checked'];function S(e){if(!e||!e.getAttribute)return;for(var i=0;i<A.length;i++){if(e.hasAttribute(A[i]))try{e.removeAttribute(A[i]);}catch(_){} }if(e.attributes){for(var j=e.attributes.length-1;j>=0;j--){var n=e.attributes[j].name;if(n.indexOf('__processed_')===0){try{e.removeAttribute(n);}catch(_){}}}}}function SA(){if(!document||!document.body)return;S(document.body);var w=document.createTreeWalker(document.body,NodeFilter.SHOW_ELEMENT);var node;while(node=w.nextNode()){S(node);}}var at=0,max=20;var it=setInterval(function(){at++;try{SA();}catch(_){}if(at>=max)clearInterval(it);},50);if(document.readyState==='complete'||document.readyState==='interactive'){try{SA();}catch(_){}}else{document.addEventListener('DOMContentLoaded',SA,{once:true});}})();",
          }}
        />
        {children}
      </body>
    </html>
  );
}
